package kr.co.mcmp.util;

import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.test.util.ReflectionTestUtils;
import static org.assertj.core.api.Assertions.assertThat;

class NginxHelmCatalogTest {
    private JdbcTemplate jdbc;
    private DatabaseInitializer initializer;

    @BeforeEach
    void setUp() {
        jdbc = new JdbcTemplate(new DriverManagerDataSource(
                "jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", ""));
        jdbc.execute("""
                CREATE TABLE SOFTWARE_CATALOG (
                    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    TITLE VARCHAR, DESCRIPTION VARCHAR, SUMMARY VARCHAR, CATEGORY VARCHAR,
                    LOGO_URL_LARGE VARCHAR, LOGO_URL_SMALL VARCHAR, MIN_CPU DOUBLE PRECISION,
                    RECOMMENDED_CPU DOUBLE PRECISION, MIN_MEMORY DOUBLE PRECISION,
                    RECOMMENDED_MEMORY DOUBLE PRECISION, MIN_DISK INTEGER, RECOMMENDED_DISK INTEGER,
                    CPU_THRESHOLD DOUBLE PRECISION, MEMORY_THRESHOLD DOUBLE PRECISION,
                    MIN_REPLICAS INTEGER, MAX_REPLICAS INTEGER, HPA_ENABLED BOOLEAN,
                    DEFAULT_PORT INTEGER, INGRESS_ENABLED BOOLEAN, CREATED_AT TIMESTAMP, UPDATED_AT TIMESTAMP)
                """);
        jdbc.execute("""
                CREATE TABLE HELM_CHART (CATALOG_ID BIGINT, CHART_NAME VARCHAR, CHART_VERSION VARCHAR,
                    CHART_REPOSITORY_URL VARCHAR, REPOSITORY_NAME VARCHAR, REPOSITORY_DISPLAY_NAME VARCHAR,
                    REPOSITORY_OFFICIAL BOOLEAN, PACKAGE_ID VARCHAR, NORMALIZED_NAME VARCHAR,
                    APP_VERSION VARCHAR, DESCRIPTION VARCHAR, CATEGORY VARCHAR, IMAGE_REPOSITORY VARCHAR,
                    TAG VARCHAR, HAS_VALUES_SCHEMA BOOLEAN)
                """);
        jdbc.execute("CREATE TABLE SOFTWARE_CATALOG_REF (CATALOG_ID BIGINT, REF_IDX INTEGER, REF_VALUE VARCHAR, REF_DESC VARCHAR, REF_TYPE VARCHAR)");
        initializer = new DatabaseInitializer();
        ReflectionTestUtils.setField(initializer, "jdbcTemplate", jdbc);
    }

    @Test
    void createsExternalChartAndIsIdempotent() {
        synchronize();
        synchronize();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM HELM_CHART", Integer.class)).isEqualTo(1);
        assertThat(jdbc.queryForObject("SELECT CHART_REPOSITORY_URL FROM HELM_CHART", String.class))
                .isEqualTo("https://cloudpirates-io.github.io/helm-charts");
        assertThat(jdbc.queryForObject("SELECT CHART_VERSION FROM HELM_CHART", String.class)).isEqualTo("0.16.8");
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM SOFTWARE_CATALOG_REF", Integer.class)).isEqualTo(1);
    }

    @Test
    void migratesExactLegacyMappingWithoutDuplicatingIt() {
        legacy(11, "Nginx for Kubernetes", "http://localhost:18084/charts", "0.1.0");
        synchronize();
        synchronize();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM HELM_CHART WHERE CATALOG_ID=11", Integer.class)).isEqualTo(1);
        assertThat(jdbc.queryForObject("SELECT PACKAGE_ID FROM HELM_CHART WHERE CATALOG_ID=11", String.class)).isEqualTo("cloudpirates-nginx");
        assertThat(jdbc.queryForObject("SELECT APP_VERSION FROM HELM_CHART WHERE CATALOG_ID=11", String.class)).isEqualTo("1.31.5");
    }

    @Test
    void preservesCustomizedRepositoryAndVersionAndOtherCatalog() {
        legacy(11, "Nginx for Kubernetes", "https://example.org/custom", "0.1.0");
        legacy(12, "Nginx for Kubernetes", "http://localhost:18084/charts", "9.0.0");
        legacy(13, "Another catalog", "http://localhost:18084/charts", "0.1.0");
        synchronize();
        assertThat(jdbc.queryForList("SELECT PACKAGE_ID FROM HELM_CHART", String.class))
                .containsExactly("mcmp-builtin-nginx", "mcmp-builtin-nginx", "mcmp-builtin-nginx");
        assertThat(jdbc.queryForObject("SELECT CHART_REPOSITORY_URL FROM HELM_CHART WHERE CATALOG_ID=11", String.class))
                .isEqualTo("https://example.org/custom");
    }

    private void legacy(long id, String title, String url, String version) {
        jdbc.update("INSERT INTO SOFTWARE_CATALOG (ID, TITLE) VALUES (?, ?)", id, title);
        jdbc.update("""
                INSERT INTO HELM_CHART (CATALOG_ID, CHART_NAME, CHART_VERSION, CHART_REPOSITORY_URL, REPOSITORY_NAME, PACKAGE_ID)
                VALUES (?, 'nginx', ?, ?, 'mcmp-builtin', 'mcmp-builtin-nginx')
                """, id, version, url);
    }

    private void synchronize() {
        ReflectionTestUtils.invokeMethod(initializer, "ensureNginxHelmCatalog");
    }
}
